export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS';
export const GET_ALL_BOOK_FAILED = 'GET_ALL_BOOK_FAILED';

export const GET_RELATED_BOOK = 'GET_RELATED_BOOK';
export const GET_RELATED_BOOK_SUCCESS = 'GET_RELATED_BOOK_SUCCESS';
export const GET_RELATED_BOOK_FAILURE = 'GET_RELATED_BOOK_FAILURE';

export const GET_REVIEW_BOOK = 'GET_REVIEW_BOOK';
export const GET_REVIEW_BOOK_SUCCESS = 'GET_REVIEW_BOOK_SUCCESS';
export const GET_REVIEW_BOOK_FAILURE = 'GET_REVIEW_BOOK_FAILURE';
