export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS';
export const GET_ALL_BOOK_FAILED = 'GET_ALL_BOOK_FAILED';

export const GET_RELATED_BOOK = 'GET_RELATED_BOOK';
export const GET_RELATED_BOOK_SUCCESS = 'GET_RELATED_BOOK_SUCCESS';
export const GET_RELATED_BOOK_FAILURE = 'GET_RELATED_BOOK_FAILURE';

export const GET_REVIEW_BOOK = 'GET_REVIEW_BOOK';
export const GET_REVIEW_BOOK_SUCCESS = 'GET_REVIEW_BOOK_SUCCESS';
export const GET_REVIEW_BOOK_FAILURE = 'GET_REVIEW_BOOK_FAILURE';

export const GET_CMS_HOME_SUMMARY = 'GET_CMS_HOME_SUMMARY';
export const GET_CMS_HOME_SUMMARY_SUCCESS = 'GET_CMS_HOME_SUMMARY_SUCCESS';
export const GET_CMS_HOME_SUMMARY_FAILED = 'GET_CMS_HOME_SUMMARY_FAILED';

export const GET_BOOK_SUGGESTION = 'GET_BOOK_SUGGESTION';
export const GET_BOOK_SUGGESTION_SUCCESS = 'GET_BOOK_SUGGESTION_SUCCESS';
export const GET_BOOK_SUGGESTION_FAILED = 'GET_BOOK_SUGGESTION_FAILED';

export const GET_BEST_USER = 'GET_BEST_USER';
export const GET_BEST_USER_SUCCESS = 'GET_BEST_USER_SUCCESS';
export const GET_BEST_USER_FAILED = 'GET_BEST_USER_FAILED';

export const GET_BEST_REVIEW = 'GET_BEST_REVIEW';
export const GET_BEST_REVIEW_SUCCESS = 'GET_BEST_REVIEW_SUCCESS';
export const GET_BEST_REVIEW_FAILED = 'GET_BEST_REVIEW_FAILED';
