export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS';
export const GET_ALL_BOOK_FAILED = 'GET_ALL_BOOK_FAILED';

export const GET_CMS_HOME_SUMMARY = 'GET_CMS_HOME_SUMMARY';
export const GET_CMS_HOME_SUMMARY_SUCCESS = 'GET_CMS_HOME_SUMMARY_SUCCESS';
export const GET_CMS_HOME_SUMMARY_FAILED = 'GET_CMS_HOME_SUMMARY_FAILED';

export const GET_BOOK_SUGGESTION = 'GET_BOOK_SUGGESTION';
export const GET_BOOK_SUGGESTION_SUCCESS = 'GET_BOOK_SUGGESTION_SUCCESS';
export const GET_BOOK_SUGGESTION_FAILED = 'GET_BOOK_SUGGESTION_FAILED';
