export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const GET_ALL_ITEM_IN_CART = 'GET_ALL_ITEM_IN_CART';
export const GET_ALL_ITEM_IN_CART_SUCCESS = 'GET_ALL_ITEM_IN_CART_SUCCESS';
export const GET_ALL_ITEM_IN_CART_FAILED = 'GET_ALL_ITEM_IN_CART_FAILED';
