export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';

export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDER_BY_ID_FAILED = 'GET_ORDER_BY_ID_FAILED';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
