export const GET_LIST_USER_NOTIFICATIONS = 'GET_LIST_USER_NOTIFICATIONS';
export const GET_LIST_USER_NOTIFICATIONS_FAILED =
  'GET_LIST_USER_NOTIFICATIONS_FAILED';
export const GET_LIST_USER_NOTIFICATIONS_SUCCESS =
  'GET_LIST_USER_NOTIFICATIONS_SUCCESS';

export const MARK_AS_SEEN_NOTIFICATIONS = 'MARK_AS_SEEN_NOTIFICATIONS';
export const MARK_AS_SEEN_NOTIFICATIONS_FAILED =
  'MARK_AS_SEEN_NOTIFICATIONS_FAILED';
export const MARK_AS_SEEN_NOTIFICATIONS_SUCCESS =
  'MARK_AS_SEEN_NOTIFICATIONS_SUCCESS';
