export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

export const GET_REVIEW_BOOK = 'GET_REVIEW_BOOK';
export const GET_REVIEW_BOOK_SUCCESS = 'GET_REVIEW_BOOK_SUCCESS';
export const GET_REVIEW_BOOK_FAILURE = 'GET_REVIEW_BOOK_FAILURE';

export const DELETE_REVIEW_BOOK = 'DELETE_REVIEW_BOOK';
export const DELETE_REVIEW_BOOK_SUCCESS = 'DELETE_REVIEW_BOOK_SUCCESS';
export const DELETE_REVIEW_BOOK_FAILURE = 'DELETE_REVIEW_BOOK_FAILURE';

export const UPDATE_REVIEW_BOOK = 'UPDATE_REVIEW_BOOK';
export const UPDATE_REVIEW_BOOK_SUCCESS = 'UPDATE_REVIEW_BOOK_SUCCESS';
export const UPDATE_REVIEW_BOOK_FAILURE = 'UPDATE_REVIEW_BOOK_FAILURE';
