export const GET_ALL_MEMBERSHIP_CODE = 'GET_ALL_MEMBERSHIP_CODE';
export const GET_ALL_MEMBERSHIP_CODE_FAILED = 'GET_ALL_MEMBERSHIP_CODE_FAILED';
export const GET_ALL_MEMBERSHIP_CODE_SUCCESS =
  'GET_ALL_MEMBERSHIP_CODE_SUCCESS';

export const BUY_MEMBERSHIP_PACKAGE = 'BUY_MEMBERSHIP_PACKAGE';
export const BUY_MEMBERSHIP_PACKAGE_FAILED = 'BUY_MEMBERSHIP_PACKAGE_FAILED';
export const BUY_MEMBERSHIP_PACKAGE_SUCCESS = 'BUY_MEMBERSHIP_PACKAGE_SUCCESS';

export const  UPGRADE_MEMBER_SHIP = 'UPGRADE_MEMBER_SHIP';
export const  UPGRADE_MEMBER_SHIP_FAILED = 'UPGRADE_MEMBER_SHIP_FAILED';
export const  UPGRADE_MEMBER_SHIP_SUCCESS = 'UPGRADE_MEMBER_SHIP_SUCCESS';
